spring:
  profiles:
    active:
      - dev
---  
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.lqz.microservicecloud.entity
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml

spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB?useSSL=false&characterEncoding=UTF-8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
      
eureka:
  client:    # 将客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true  # 访问路径可以显示ip地址

info:
  app.name: lqz-microservicecloud
  company.name: www.lqz.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.lqz.microservicecloud.entity
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml

spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB?useSSL=false&characterEncoding=UTF-8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
      
eureka:
  client:    # 将客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true  # 访问路径可以显示ip地址

info:
  app.name: lqz-microservicecloud
  company.name: www.lqz.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$